const config = {
  use: {
    catalog_url: 'api/catalog/catalogs',
    catalog_prod_url: 'api/catalog',
    category_url: 'api/catalog/categories',
    product_links: 'api/catalog/listentrylinks',
    products_url: 'api/catalog/products',
    product_url: 'api/catalog/product',
    search_property_url: 'api/catalog/dictionaryitems/search',
    search_products_url: 'api/catalog/search/products',
    stores_by_catalog: 'api/catalog/catalogs/catalogID/stores',
    customers_email_url: 'api/customers/email',
    customers_url: 'api/customers',
    catalog_association_url: 'api/catalog/products/associations',
    stores_url: 'api/stores',
    property_url: 'api/catalog/properties',
    product_association_url: 'api/catalog/products/associations',
    inventory_url: 'api/inventory/fulfillmentcenters',
    graphql_url: 'storefront/graphql',
    stores_allowed_url: 'api/stores/allowed',
    add_product_to_catalog_url: 'api/ProductManagement/addproducttocatalog',
    get_user_info: 'api/platform/security/users',
    update_security_users: 'api/platform/security/users',
    price_assigment: 'api/pricing/assignments',
    members_search: 'api/members/search',
    identity_url: 'api/identity',
    roles_search: 'api/identity/roles/search',
    member_url: 'api/members/',
    customer_order_url: '/#/workspace/orders',
    storefront_catalog_product_url: '/storefrontapi/catalog/product',
    search_order_url: '/api/order/customerOrders/search',
    order_url: 'api/order/customerOrders',
    remove_products_url: 'api/catalog/products',
    listentries_url: 'api/catalog/listentries',
  },
};

export default config;
